### ISSUE TITLE
trim_trailing_whitespace moves caret

### ISSUE THREAD

**Issue by theoy** [editorconfig/editorconfig-vscode#47] opened 2016-04-14 23:28 UTC
_( ported from Microsoft/vscode-editorconfig#24 )_

Repro'd on [editorconfig v0.2.7](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig):
1. Enable autosave in VS Code (e.g. in user settings) - great for users who are used to using Git to back up their code.
2. Open up a workspace that lacks VS Code workspace settings for `files.trimTrailingWhitespace`.
3. In the same workspace, create a .editorconfig, setting `trim_trailing_whitespace = true`

Type some code with spaces, then rest (wait for autosave delay).

**Expected**: Caret position remains, trailing whitespace preceding the caret is **not** trimmed
**Actual**: All trailing whitespace is trimmed, causing the caret to move and the code (whitespace) that was under composition to be deleted.

Note, this caused me to stop using `trim_trailing_whitespace` for a while, before I realised that enabling the matching VS Code option overrode the behaviour to be correct. However, figured it was worth reporting so that this could be improved for new users.

**Comment by SamVerschueren** [comment] 2016-04-15 06:25
This means we should be able to distinguish the difference between an `autoSave` and a manual `save`.  A manual save should still trim all the whitespace. This is the same behaviour when using the editors `trimTrailingWhitespace` feature.

@bpasero is it possible to distinguish these save events? I had a look in the callback of the `onDidSaveTextDocument` event but it doesn't have something like `autoSaved: true`. If this is not possible yet I will create a new issue in the VS Code issue tracker.

**Comment by bpasero** [comment] 2016-04-15 06:33
I do not think we expose this to extensions (though we would know it on the internal side). @jrieken would know.

**Comment by SamVerschueren** [comment] 2016-04-15 06:42
Thanks for the quick response @bpasero . Created an issue for this.

**Comment by jrieken** [comment] 2016-04-15 09:52
Fair request, today we only send the [TextDocument](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3302) in the event which wasn't the best choice. Unsure how we would make such a chance without breaking the API...

**Comment by NinoFloris** [comment] 2016-05-11 01:26
Nice to find this issue

I would love it if you could at least not trim it if there is no text in front of it? 

As currently if I want to start by indenting a line and then type my text I have to be faster than my autosave or I will be yanked back to the start.
Very unpleasant and currently my trim_trailing_whitespace is commented out because of this.

**Comment by jedmao** [comment] 2016-05-11 01:35
@SamVerschueren, even if we could distinguish between a manual vs. auto-save, I'm not sure we should do anything differently. We need to be really cautious here, because we run the risk of allowing the user to save a file with trailing whitespace. Whether it was a manual or auto-save does not matter. What matters is that it would then be possible for a user to deviate from the EditorConfig configuration and that does not sit well with me. As such, I suggest we keep the feature as-is.

Open to any suggestions, but I don't think treating auto-save differently than a manual save is the solution here (if any).

**Comment by theoy** [comment] 2016-05-11 02:10
In a previous lifetime, I spent quite a few years as a dev on the VS IDE team, so here's my two cents FWIW... 

I think there are 3 possible ways to design this for editors in general:
* If the editor in use supports virtual positions (caret in positions that don't exist in text), then trim and ensure the caret is in the same (virtual) position after save. However, not all editors support virtual caret positions.
* On autosave only, trim only whitespace beyond the caret (this UX choice works well with the recognition that the user didn't really initiate the save)
* Trim only whitespace beyond the caret (always)

I am not a purist, and I don't think this is an architectural debate. This kind of text transform is not any more special than any other automated transform, along the lines of auto-normalise whitespace, auto-indent, auto-format, auto-complete constructs.

All of these sorts of transforms are arbitrary to the editor extender, and nobody can anticipate all the types of DSLs or cosmetic transforms people may imagine up.

Thus, I don't think there's any long term architectural harm in special-casing the caret. From a UX point of view, this could always potentially be interfered by another extension that processes after this. Personally I think the UX benefit for the typical case outweighs concerns about consistency.

Just my two cents :smile:

**Comment by jedmao** [comment] 2016-05-11 04:28
I think I have a viable solution!
  1. Trim ALL trailing whitespace, regardless of manual or auto-save.
  1. If auto-save, restore leading whitespace to cursor position.
    - Makes the file dirty again.
    - The file adheres to the EditorConfig configuration at all times.
    - User does not lose their cursor position.

How does this sound for a potential strategy?

**Comment by SamVerschueren** [comment] 2016-05-11 06:02
@jedmao I think you will notice the flickering. And because we can't determine the difference between an auto-save or a manual save, `2` can't be determined.

**Comment by jedmao** [comment] 2016-05-11 06:59
@SamVerschueren I understand that. My suggestions were making the assumption that the distinction could be made in the future.

**Comment by SamVerschueren** [comment] 2016-05-11 07:02
Oh ok, missed that :). Then I'm 👍  on the idea.

But because we are iterating over every line, we might as well just skip the trailing whitespace on the line of the cursor. This will solve the flickering issue. But let's just wait until we can determine the type of save :).

**Comment by jedmao** [comment] 2016-05-11 07:03
@SamVerschueren it's important that we also trim the line with the cursor, but restore the cursor to its original position. Only this way can we ensure the file on the file system adheres to the EditorConfig configuration.

**Comment by jedmao** [comment] 2016-05-11 07:04
In fact, we should probably do the same thing on manual save. The user might be confused that the file remains dirty, however.

**Comment by theoy** [comment] 2016-05-11 17:11
@jedmao -
> Makes the file dirty again.

Would dirtying the file trigger another autosave delay? Would be important to check to make sure that a re-dirtying approach doesn't cause infinite resave loops. 

> file system adheres to the EditorConfig configuration.

Is this really important for code that is in the process of being edited? Autosave or not, if there is trailing whitespace preceding the cursor, it's very likely that the user will make subsequent edits/saves.

I'm also a little confused, because even though having an .editorconfig is very useful, I don't think there's a user expectation that it can't be thwarted. For example, any other tool (either editor or build script) could edit the code and cause deviations from the editorconfig preference. To me this is a best effort thing.

If you can help me understand, that'd be great.

**Comment by jedmao** [comment] 2016-05-11 17:21
@theoy I believe auto-save works on a timeout, so it wouldn't check the dirty state over and over; thus, no infinite loop. Definitely something to double check as the feature is implemented, however.

I agree that the user is very likely to make subsequent edits/saves after an auto-save, but it's definitely no guarantee. I'm imagining someone finishes a line of though, steps away from their computer for a while and comes back to see the file is already saved (not dirty). This is basically what I'm trying to prevent. True, you can always add a linter to your project, but I think an official EditorConfig plugin should do its best to prevent weird things like this from being introduced. I mean, that's the whole point of EditorConfig, right? To prevent violations from slipping in like this? I'm very concerned about those types of issues.

I think it's more than a "best effort" kind of thing. I think we need to be creative to ensure the right strategies are implemented to ensure weirdness and confusion are not introduced.

**Comment by jedmao** [comment] 2016-05-11 17:26
@SamVerschueren do you think you can attach an animated GIF that shows the flickering issue you're talking about? I just want to make sure I fully understand it and prevent it from happening, if at all possible.

**Comment by SamVerschueren** [comment] 2016-05-11 17:29
If I find some time I will add it. I'm not sure either though but I can imagine that it will be visible. But if it's not, better for us ;).

**Comment by theoy** [comment] 2016-05-11 17:39
@jedmao 
> I think it's more than a "best effort" kind of thing. I think we need to be creative to ensure the right strategies are implemented to ensure weirdness and confusion are not introduced.

Fair enough - I'm happy as long as it doesn't cause an infinite resaving loop. One more thing to consider though, is the prebuilt VS Code behaviour. Since discovering this issue, I've turned on VS Code's built-in trim trailing whitespace option (`files.trimTrailingWhitespace`). It behaves such that:
* if Explicit Save - trim all trailing space (potentially moving the caret)
* if Auto-Save - trim only whitespace that is after the caret (can cause trailing whitespace to be emitted to disk).

At least for the VS Code extension for editorconfig, you may wish to consider keeping behaviour consistent with VS Code's built-in behaviour, for the sake of getting users to adopt `.editorconfig` in lieu of `.vscode/settings.json`.

**Comment by jedmao** [comment] 2016-05-11 18:11
@theoy that's a very good point. I do believe the plugin should have a consistent philosophy with the editor, so I think I'm OK with doing just as you suggested.

**Comment by jedmao** [comment] 2016-05-11 18:12
It looks like now we just need a way to distinguish between manual and auto-save. @SamVerschueren, did we create an issue on the vscode project to request this feature yet? If so, please link it to this thread.

**Comment by SamVerschueren** [comment] 2016-05-11 19:27
Yes https://github.com/Microsoft/vscode/issues/5305

**Comment by Ilyes512** [comment] 2017-03-22 09:43
Any updates on this?

**Comment by SamVerschueren** [comment] 2017-03-22 10:26
See the VS Code issue I linked. If we can't distinguish between these two events, I don't think we are able to solve this. Unless you have any fresh ideas.

**Comment by jrieken** [comment] 2017-03-22 10:28
@SamVerschueren We cannot add those information to the `onDidSave`-event, tho they are exposed on the `onWillSave`-event

**Comment by SamVerschueren** [comment] 2017-03-22 10:29
Aha, then we might be able to solve this. Will have a look when I find some time. Thanks @jrieken!

**Comment by jedmao** [comment] 2017-03-22 13:31
@jrieken, I would be more interested in running the `editor.action.trimTrailingWhitespace` command so that we can leverage the editor to do it for us. I've done this successfully in this extension, but unfortunately it only works on visible text editors. This isn't ideal for scenarios in which someone triggers a "save all" command, in which there are many text documents w/o visible editors. Also, another thing missing from the command is the ability to send the "reason" (i.e., manual or auto-save).

**Comment by jrieken** [comment] 2017-03-22 14:17
We have a setting `files.trimTrailingWhitespace` and when that is set to `true` this will happen on [save](files.trimTrailingWhitespace). What the command does isn't specified and *not* part of the API, don't expect it to work in all scenarios. So, if there is anything missing the above mentioned save participant doesn't do, there is enough API to do this

**Comment by jedmao** [comment] 2017-03-22 15:00
It would be great if a similar setting were exposed for each editor, so that we can apply it on a file by file basis, just like insertSpaces.

**Comment by jedmao** [comment] 2017-04-09 04:51
@theoy can you confirm that this is [fixed in v0.6.3](https://github.com/editorconfig/editorconfig-vscode/pull/130)?

**Comment by jminer** [comment] 2017-05-06 07:24
Using 0.9.3 and VS Code 1.12.1, I am still seeing the bug using the steps in the original report.

**Comment by jedmao** [comment] 2017-05-06 13:46
@jminer see https://github.com/Microsoft/vscode/issues/23983

**Comment by jminer** [comment] 2017-05-06 20:55
Thanks, but I am not seeing https://github.com/Microsoft/vscode/issues/23983. My .editorconfig file doesn't have `end_of_line` set. Additionally, in that issue, the caret moves to the beginning of the file, but I am seeing the caret stay at the end of the line (the line just gets shorter when the whitespace is removed).

**Comment by jedmao** [comment] 2017-05-09 17:01
@jminer can you tell me what you see in your EditorConfig output window on a file save? Trying to figure out of it's applying the built-in trim trailing whitespace command or the manual one.

**Comment by jminer** [comment] 2017-05-12 02:11
Sure, this line is printed when I let it autosave, and the caret moves:

    src/parser.rs: editor.action.trimTrailingWhitespace

If I disable `trim_trailing_whitespace` in .editorconfig and run the "Trim Trailing Whitespace" command using Ctrl+Shift+P and searching for it, or by Ctrl+K Ctrl+X, then the same thing happens. The whitespace before the caret is removed and the caret moves to the left.

**Comment by jedmao** [comment] 2017-05-22 01:38
@jminer this "should" be fixed in the next vscode release. See https://github.com/Microsoft/vscode/issues/23983#event-1087502108

**Comment by okonon** [comment] 2017-09-21 19:32
This is still an issue

**Comment by jedmao** [comment] 2017-09-21 20:54
@okonon please be more specific about exactly what's happening in your scenario, if you would.

**Comment by jminer** [comment] 2017-09-22 01:52
I'm using VS Code 1.16.1 with EditorConfig 0.10.1, and I can still reproduce the bug using the steps listed in the original post. I also see the same line printed in the EditorConfig output window that I reported earlier.

To avoid the bug, I've deleted `trim_trailing_whitespace` from my .editorconfig file for periods of time. Sometimes I use the built-in `files.trimTrailingWhitespace` setting instead because it works perfectly, but I need per-project whitespace trimming, and I like autosave, so lately I've kind of gotten used to not pausing after typing a space.

**Comment by jedmao** [comment] 2017-09-29 06:40
I wish I could help, but I need to spend more time with my family and less with code. Willing to accept a PR.

**Comment by dgileadi** [comment] 2017-10-07 01:05
I've done some looking into this and I know why it's happening. The vscode function `trimTrailingWhitespace` correctly ignores trailing whitespace at all of the cursors that are passed into it. The problem is the `editor.action.trimTrailingWhitespace` command that this extension uses (which is the same as the Ctrl+K Ctrl+X menu command). Internally that `TrimTrailingWhitespaceCommand` object calls the `trimTrailingWhitespace` function and always passes it an empty array of cursors. This behavior makes sense in the context of a menu command, but of course doesn't make sense when the command is generated by an auto-save.

Incidentally The reason the `files.trimTrailingWhitespace` setting doesn't trim whitespace at the cursor(s) is that it doesn't use the `TrimTrailingWhitespaceCommand`. Instead it calls `trimTrailingWhitespace` directly and passes it an array of cursors.

The best fix I can think of is to implement [vscode #24400](https://github.com/Microsoft/vscode/issues/24400), passing along a `reason` of `auto-save`. I've implemented this locally and it solves the problem for me. I plan on making a PR for vscode and a PR for this extension.

**Closed** 2017-10-25 17:48 UTC
Labels: bug, help wanted

**Comment by tofanelli** [comment] 2017-11-24 20:53
Version 1.18.1 and the cursor still goes to last line on Manual Save...

**Comment by jedmao** [comment] 2017-11-24 21:01
@tofanelli this issue is about auto-save. I can't repro your manual save issue. It could very well be another extension. Please submit a separate issue if you continue to experience it.

**Comment by dgileadi** [comment] 2017-11-24 23:00
I coded my fix to only apply to auto-save. I figure if you’re saving manually, you expect the saved file to conform to your editorconfig preferences.

**Comment by VitaliyR** [comment] 2018-04-25 12:53
Any updates on this one? Really annoying

**Comment by jedmao** [comment] 2018-04-25 13:03
@VitaliyR please submit a separate issue with steps to reproduce. And disable all other extensions.

**Comment by Tectract** [comment] 2022-01-10 20:34
Did this ever get fixed? Trim whitespace on every line except the currently careted line was a standard option back in NetBeans, like a decade ago! This is so frustrating.
