### ISSUE TITLE
EditorConfig extension prevents workspace setting for editor.tabSize from overriding user setting

### ISSUE THREAD

**Issue by c32hedge** [editorconfig/editorconfig-vscode#265] opened 2020-02-05 21:20 UTC
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.41.1`            | `0.14.4`             |

### Root `.editorconfig` File

None

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `3`     | `6`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

Any (I tried .ts and .js files)

### Expected behavior

When the EditorConfig extension is enabled and there is either:
* No `.editorconfig` file in the tree
* No `indent_size` setting in any `.editorconfig` file in the tree that applies to a given file

Then VSCode should use the Workspace setting, not the User setting, for number of spaces.

### Actual behavior

Opening a file shows the following:

![image](https://user-images.githubusercontent.com/8810829/73883689-60557780-4832-11ea-8f6b-22b21b0e4d79.png)

If I click the Spaces control and select "Indent Using Spaces" from the Select Action dropdown, I see:

![image](https://user-images.githubusercontent.com/8810829/73883835-a0b4f580-4832-11ea-893f-ad7c797dc6f9.png)
(Note that 6 is the actual selected value, despite 3 showing "Configured Tab Size" next to it.)

I confirmed that if I try editing the file, it is using 6 spaces instead of the expected 3.

### Additional comments or steps to reproduce

If I disable the EditorConfig extension and open a file, I see 3 as the selected value in both places, as expected.

Full version information for VSCode:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-72-generic

It looks like this may have been seen before as #114, but was closed without being fixed.

**Comment by TriMoon** [comment] 2020-03-01 11:00
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic
```
Completely bugged...
I have tabsize at **default** both in workspace and user settings.
Yet the **settings** in `.editorconfig` are totally ignored. :cry:

**Comment by TriMoon** [comment] 2020-03-02 11:05
FYI: I'm now converting to [using per language settings](https://stackoverflow.com/a/42281352) in the workspace config file(s) with this extension **disabled**...

**Comment by jedmao** [comment] 2020-11-24 22:26
It looks like this is now fixed, as I cannot reproduce. I deleted my `.editorconfig` file and setup my project with a user setting of `3` and a workspace setting of `6` and I'm getting 6 for both the configured tab size as well as the selected tab size.

**Closed by jedmao** 2020-11-24 22:26 UTC
