### ISSUE TITLE
Do not activate eslint server for projects without eslint config files.

### ISSUE THREAD

**Issue by ravshansbox** [editorconfig/editorconfig-vscode#177] opened 2017-10-23 19:26 UTC

**Comment by jedmao** [comment] 2017-10-23 21:03
Duplicate of #52. This doesn't make sense, because the `.editorconfig` file could exist outside the project root(s). Also, you can either disable the extension for the project in question or add an `.editorconfig` file at the root(s) with `root = true`.

**Closed by jedmao** 2017-10-23 21:03 UTC
Labels: duplicate

**Comment by ravshansbox** [comment] 2017-10-24 07:03
I'm sorry, I've filed the issue to the wrong repository.
