### ISSUE TITLE
Saving huge files flashes the dirty circle indicator in open editors rapidly until it is saved to disk

### ISSUE THREAD

**Issue by Tyriar** [editorconfig/editorconfig-vscode#58] opened 2016-07-05 05:48 UTC
_From @Tyriar on July 5, 2016 3:43_

- VSCode Version: Code - Insiders 1.3.0-insider (0c5f6e8867fb117b6fa41cc647dc650bb9856dc4, 2016-07-04T09:39:57.773Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Steps to Reproduce:

1. Turn on open editors if not already
2. Open a huge file (mine was 18000 lines)
3. Dirty
4. Save, observe the circle indicator flashing rapidly, presumably until it is actually saved to disk. I saw this on an SSD, it will probably be a lot worse on a HDD. I also noticed that the save trimmed a bunch of whitespace, so that may be related.

_Copied from original issue: Microsoft/vscode#8744_

**Comment by Tyriar** [comment] 2016-07-05 05:48
_From @bpasero on July 5, 2016 4:52_

I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by SamVerschueren** [comment] 2016-07-05 06:29
@Tyriar does this also happen when you have `trim_trailing_whitespace` disabled? The thing is that this extension iterates over all the lines and removes the trailing whitespace, which can actually take a while on very large files.

If `trim_trailing_whitespace` is the cause of this issue, you can always have a look at the VS Code settings and make sure that `files.trimTrailingWhitespace` is set to `true` AND `trim_trailing_whitespace` of `.editorconfig` is `true`. This will trigger the [native VS Code `trimTrailingWhitespace` method](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/transformations/trimTrailingWhitespace.ts#L22-L34).

**Comment by bpasero** [comment] 2016-09-01 13:49
PLEASE fix this...

**Comment by SamVerschueren** [comment] 2016-09-01 14:19
@bpasero Is this still happening after making sure the native trim trailing whitespace is being used?

**Comment by bpasero** [comment] 2016-09-01 14:31
No clue but I get a bug once per day that the dirty indicator flickers :)

**Comment by SamVerschueren** [comment] 2016-09-01 14:51
I was thinking about this, it might be caused by autoSave although not sure though. Have to check when I find some time, quite busy lately.

**Comment by SamVerschueren** [comment] 2016-10-12 08:24
Might be fixed (although not sure) if #76 is being fixed (see PR #80). This will use the `onWillSaveTextDocument` API.

**Comment by jedmao** [comment] 2016-10-19 06:48
@Tyriar, please confirm that this is fixed in #80, published as version 0.3.4. Thanks!

**Comment by SamVerschueren** [comment] 2016-10-19 09:18
I don't think @Tyriar or @bpasero where experiencing this issue themselves? Did you guys create this because it was reported multiple times by users in the VS Code issues? I believe this should be fixed as we aren't editing stuff ourselves. We just provide `TextEdit` objects to VS Code and it handles that itself. But it would be nice if someone could confirm this.

**Comment by bpasero** [comment] 2016-10-19 09:20
I am not using editorconfig extension so I do not feel qualified to answer.

**Comment by Tyriar** [comment] 2016-10-19 15:13
I was experiencing this personally, not sure what file I was using though. I haven't seen this being an issue for a long time.

**Comment by jedmao** [comment] 2016-10-19 15:39
Closing until re-reported.

**Closed by jedmao** 2016-10-19 15:39 UTC
