### ISSUE TITLE
Cursor position is reset to the center of the line while typing

### ISSUE THREAD

**Issue by jpvantuyl** [editorconfig/editorconfig-vscode#165] opened 2017-07-31 23:43 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.8.0
vscode-markdownlint|Dav|0.10.0
githistory|don|0.2.2
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
gc-excelviewer|Gra|1.1.15
Ionide-fsharp|Ion|2.28.0
Go|luk|0.6.63
mssql|ms-|1.1.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
vscode-docker|Pet|0.0.16
java|red|0.7.0
code-settings-sync|Sha|2.8.2
code-spell-checker|str|1.3.2
vscode-react-native|vsm|0.4.0

---

Steps to Reproduce:

1. Ensure that an editor config file does not exist.
2. Open a document of any type (e.g. Readme.md)
3. Type furiously.  Just mash on the keyboard.  Or better yet, type "The quick brown fox jumped over the lazy dog"
4. Observe that the insertion point/cursor is not at the end of the line.  You just typed gibberish.  In the screencap below, the "he" from "the" has been moved to the end of the line.

![image](https://user-images.githubusercontent.com/1139835/28729953-2bda1bae-7383-11e7-9c15-c9ce5d7dd4b8.png)

Disabling the editorconfig extension resolves the issue.

Reproduces without extensions: No

**Comment by jedmao** [comment] 2017-08-07 18:11
Looks like a race condition. Unfortunately, I don't think we have any control over it, as it's executed as a built-in vscode operation.

**Comment by AlesMenzel** [comment] 2017-08-12 08:41
Can confirm this happens on the newest Win 64bit build, i have only the editor config extension enabled and `trim_trailing_whitespace = true` in my config.

VS Code config:
```
{
    "files.autoSave": "afterDelay",
    "editor.renderWhitespace": "all"
}
```

It is really annoying, making this extension not usable.

PS: VS Code built in trimming does not remove trailing spaces on the line where the cursor is.

**Comment by AlesMenzel** [comment] 2017-08-12 08:49
Here is a recording: 
![](http://g.recordit.co/Kod0EyPE3n.gif)

**Comment by jedmao** [comment] 2017-08-12 19:58
Ahh, you're right. The built-in operation does not do this. I had used the built-in operation before, but [had to revert it](https://github.com/editorconfig/editorconfig-vscode/pull/133) because it wasn't working for the "Save All" operation. I'm very busy with a newborn right now, but a PR would be welcome if you want to look into it.

**Comment by darthsoup** [comment] 2017-12-11 14:06
can confirm this on 1.18.1 64bit on OSX

**Comment by yoyo930021** [comment] 2018-01-20 16:32
Me too.
output:
editor.action.trimTrailingWhitespace

**Comment by DanielPe05** [comment] 2018-01-23 02:21
As a temporary fix you can set the autoSave delay to something like 900ms. This solution is not ideal but at least a workaround for now. This problem makes the extension pretty much unusable.
```
"files.autoSaveDelay": 900 
```

**Comment by jedmao** [comment] 2018-01-23 04:51
I am unable to reproduce this ATM. Can anyone repro on the latest release, v0.12.0?

**Comment by jpvantuyl** [comment] 2018-01-24 15:21
I'm still able to reproduce the issue with v0.12.0 of the editorconfig extension and v1.19.2 of code running on Windows 10.

**Comment by jedmao** [comment] 2018-01-24 15:31
I cannot reproduce. Is there any more information that might help me reproduce?

**Comment by darthsoup** [comment] 2018-01-25 11:02
It seems to be fixed in my vscode with the new version

**Comment by jedmao** [comment] 2018-12-25 09:39
Closing sure to inactivity and because it seems fixed until I get a new report.

**Closed by jedmao** 2018-12-25 09:39 UTC
