### ISSUE TITLE
Trimming whitespace/inserting newline broken?

### ISSUE THREAD

**Issue by spencerhakim** [editorconfig/editorconfig-vscode#150] opened 2017-05-02 19:40 UTC
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.11.2`            | `0.9.3`             |

### Root `.editorconfig` File

```ini
root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4

; Golang and Makefile
[{*.go,Makefile}]
indent_style = tab

; JSON, Markdown, and YAML (and similar)
[*.{json,yml,yaml,babelrc,eslintrc,eslintrc.json,gqlconfig,md,markdown}]
indent_size = 2

```

Are there any other relevant `.editorconfig` files in your project? **No**

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

Any

### Expected behavior

Trim whitespace and insert final newline

### Actual behavior

No trimming or inserted newline. Other settings (such as indent size) behave correctly.

### Additional comments or steps to reproduce

I've been using this config without issue for months, and just noticed it stopped working. Tried disabling other extensions in case of a conflict, but it didn't make a difference. Looking at VSCode's Output window, I see EditorConfig prints the following whenever I save a file: `No configuration found for pre-save.`

**Comment by jedmao** [comment] 2017-05-03 21:20
Do you have any user or workspace settings in the template provided above?

**Comment by spencerhakim** [comment] 2017-05-04 03:31
Nope, double-checked and I never touched those properties since it was always covered by my .editorconfig. Do I need to change them from the defaults?

**Comment by jedmao** [comment] 2017-05-04 05:41
Shouldn't need to. Just asking because it's historically been difficult to reproduce peoples' issues so I need all the information I can get. That's why the issue template is so long. I'll try to repro when I get a moment.

**Comment by SamVerschueren** [comment] 2017-05-04 07:01
Seem to have the same issue in `final-newline` https://github.com/SamVerschueren/vscode-final-newline/issues/17. Will also try to have a look.

**Comment by spencerhakim** [comment] 2017-05-05 16:26
Updated to VSCode 1.12.1 today and everything is working again, I'll leave it up to someone else if this issue should be closed or investigated further. For the record, whenever I save now I see the following in the output window:

```
[file path]: setEndOfLine(LF)
[file path]: editor.action.trimTrailingWhitespace
[file path]: insertFinalNewline(LF)
```

**Comment by jedmao** [comment] 2017-05-05 16:40
@spencerhakim I'm so glad I added that logging as a new feature. It's so incredibly useful for cases like these! Thanks for the update and I'll go ahead and close this for now unless it resurfaces. Looks like it was a vscode issue.

**Closed by jedmao** 2017-05-05 16:40 UTC

**Comment by ronak1009** [comment] 2017-05-15 06:54
I got the root cause.
**files.insertFinalNewline : true** is not working, because it is interfering with the HTML-CSS-JS formatting plugin.
If you don't have these plugin, then the setting works perfectly. Can this be considered as an issue on those plugins ?

**Comment by jedmao** [comment] 2017-05-15 13:51
If this plugin works fine without another plugin installed, then yes. The issue is with the other plugin.
