### ISSUE TITLE
Opening a file changes its line endings even though no edits have been made

### ISSUE THREAD

**Issue by robertwahler** [editorconfig/editorconfig-vscode#115] opened 2017-03-08 14:32 UTC
With this plugin enabled, opening a file and making zero changes, automatically changes its line endings to match .editorconfig settings.  Is this intended behavior?

I would have thought that .editorconfig settings would only be applied on save or on first edit. The current setting makes this .editorconfig implementation difficult to use when embedded vendor code is opened (i.e. from a subrepo).

**Comment by jedmao** [comment] 2017-03-08 14:40
Duplicate of #57

**Comment by robertwahler** [comment] 2017-03-08 14:56
Sorry for the duplicate. I only reviewed open issues and assumed this had to be a bug because who would want their editor changing code when you are simply inspecting referenced code in submodules?  As I understand, the issue is with VSCode itself.  Maybe if you leave that issue open until the editor VSCode is fixed, that will cut down on the duplicate issues?

Thanks for all your efforts. I'll just disable this plugin for now.

**Comment by SamVerschueren** [comment] 2017-03-08 15:07
It has nothing to do with the editor if I can recall correctly. It's because git changes the line endings upon checkout. Not sure anymore, on mobile so can't look into it too much.

**Comment by robertwahler** [comment] 2017-03-08 16:04
It is true that Git can change line endings but not if `git config core.autocrlf false` is set (my case).  This issue is a design issue with this plugin. The issue is that it unexpectedly changes line endings marking the file dirty even though no user changes have been made to the file.

**Comment by jedmao** [comment] 2017-03-08 18:39
@SamVerschueren this has nothing to do with git. He's right, actually. Everyone was right from the beginning. I just created a mixed line ending file and opened it w/o the extension enabled and vscode doesn't do anything to the file unless you switch your line ending setting after the file has been opened.

The fact that the extension actually changes the line endings on file open might be a limitation of the vscode API, but I haven't discovered if there's a way around it yet. I'm reopening this issue.

**Comment by jedmao** [comment] 2017-03-08 23:04
I opened an issue here: https://github.com/Microsoft/vscode/issues/22259

**Comment by jedmao** [comment] 2017-03-10 19:21
@SamVerschueren, @robertwahler I have a fix up on https://github.com/editorconfig/editorconfig-vscode/pull/116, but I'm hesitant to release it because of the implications and fears of modifying the file *after* save.

I can't do it before save, because [vscode detects the most common line endings on file open and uses that for the save](https://github.com/Microsoft/vscode/issues/22259#issuecomment-285321923). Pending https://github.com/Microsoft/vscode/issues/15510, I'm not sure what we can do other than modify the file *after* save.

Now, I've tested this on my local machine and vscode seems to pick up the file changes instantly, changing the LF to CRLF in my status bar or vice versa. I'm a bit concerned that it won't always be so graceful, however. Looking for guidance or maybe we just wait for https://github.com/Microsoft/vscode/issues/15510.

What do y'all think?

**Comment by robertwahler** [comment] 2017-03-11 16:12
Thanks for this @jedmao! 
 
I'm not familiar enough with vscode to give helpful guidance on the fallout issue.  I would hope that the vscode will expose the needed API quickly.  That said, I'd be happy to have the patch now rather than wait.

**Comment by jedmao** [comment] 2017-03-11 17:42
I have one more idea before save I'd like to try.

**Comment by jedmao** [comment] 2017-03-11 19:17
Yes! Fixed it properly in #116, published as v0.6.1.

**Closed by jedmao** 2017-03-11 19:17 UTC
Labels: Accepting PRs, bug

**Comment by romp13** [comment] 2018-10-22 07:46
I'm having problems with mixed line endings files. Any time I touch a file with mixed EOL, the file gets normalized instead of only modifying the edited lines. This issue is marked as closed but in #116 the fix seems to be reverted. Can somebody help?
