### ISSUE TITLE
Plugin prevents Preview Mode from working

### ISSUE THREAD

**Issue by MarkyMarkNo1** [editorconfig/editorconfig-vscode#88] opened 2016-11-14 15:46 UTC
I'm recognizing this plugin, if an .editorconfig is present, preventing VSCode's [Preview mode](http://code.visualstudio.com/docs/editor/tabs#_preview-mode) from working. 

Instead of utilizing a Preview, each file opens in a separate Edit mode tab immediately and prompts to save changes - without having even applied any kind of change - when attempting to close them?

Thank you!

**Comment by SamVerschueren** [comment] 2016-11-14 18:37
Duplicate of #57

**Closed by SamVerschueren** 2016-11-14 18:37 UTC

**Comment by jedmao** [comment] 2017-03-11 19:19
@MarkyMarkNo1 fixed it properly in #116, published as v0.6.1.

**Comment by MarkyMarkNo1** [comment] 2017-03-11 23:47
Thx a lot, I'll give it a try 👍
