### ISSUE TITLE
editorconfig is breaking the detectIndentation on vscode

### ISSUE THREAD

**Issue by tinchoz49** [editorconfig/editorconfig-vscode#51] opened 2016-05-14 14:40 UTC
Hi guys! 

I noticed that with the editorconfig extension the detectIndentation on vscode is not working until i triggered manually.

Steps to reproduce:
```Tested without having an .editorconfig in the project.```
1. Open a package.json (indent=2) with the extension installed and the indentation of the editor is 4.
2. Remove the extension and try again the first step. The detectIndentation works again.

Thanks! excellent work with this extension!

**Comment by jedmao** [comment] 2016-05-16 02:37
Sorry you're having this issue! Thanks for the steps to reproduce. I'm definitely not going to have any time to fix the issue this week, but I maybe the following week.

Also, I'm accepting pull requests, so if you have a fix then I will gladly merge and publish.

**Comment by mschuckmann** [comment] 2016-08-04 00:26
Yep having the same problem, very annoying. I want use editorconfig for other things but it totally breaks the indentation detection.

**Comment by jedmao** [comment] 2016-08-04 01:55
Can you show me what your `.editorconfig` file looks like? And tell me what file names are showing the issue?

**Comment by mschuckmann** [comment] 2016-08-04 19:28
I am definitely seeing the problem on .cpp, .h, .py files I didn't test any others
Below is my current .editorconfig file

~~~
[*]
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
~~~

**Comment by jedmao** [comment] 2016-08-04 20:23
Aha, so you don't actually have any indentation settings at all and the plugin is still intercepting the native indentation detection? This helps a lot!

**Comment by benmosher** [comment] 2016-09-14 18:20
I'm seeing this, as well. My suspicion--from scanning the code--is that this plugin is merging the VS Code defaults (via `DocumentWatcher#getDefaultSettings`) with a blank config provided by `editorconfig.parse` when either 

- there is no `.editorconfig` in any ancestor folder (my case)
- there is no matching `.editorconfig` spec for the provided filepath (@mschuckmann's case, if I read correctly)

I think a viable fix might be to [not set this line](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/DocumentWatcher.ts#L176) if the options provided from `editorconfig.parse` doesn't explicitly specify tab/space settings (i.e. if both `insertSpaces` _and_ `tabSize` are being defaulted).

But I'm any not super familiar with VS Code extensions 😅

**Comment by jedmao** [comment] 2016-09-23 11:40
Fixed in https://github.com/editorconfig/editorconfig-vscode/pull/70

**Comment by jedmao** [comment] 2016-09-23 11:40
Fixed in https://github.com/editorconfig/editorconfig-vscode/pull/70

**Comment by jedmao** [comment] 2016-09-23 11:40
Fixed in https://github.com/editorconfig/editorconfig-vscode/pull/70

**Comment by jedmao** [comment] 2016-09-23 11:40
Fixed in https://github.com/editorconfig/editorconfig-vscode/pull/70

**Closed by jedmao** 2016-09-23 11:40 UTC
Labels: bug, help wanted

**Comment by Pointotech** [comment] 2022-11-30 20:46
Is there any way to get the EditorConfig plugin to override the VS Code settings for indentation? Isn't that the whole point of this plugin?
