### ISSUE TITLE
Previously-formatted files have pending changes when opened even if no changes occurred

### ISSUE THREAD

**Issue by simonua** [editorconfig/editorconfig-vscode#100] opened 2017-03-01 20:54 UTC
I apologize as I don't have much information here. I have formatted and saved all files after adding our .editorconfig while. Regularly, when opening such a file, it is marked as edited and requires saving in VS Code. When saving and checking the file difference in git, nothing is different. When attempting to stage the file it (correctly) drops out of the working copy as nothing is different. I am not certain why the file is touched but it did start after adding the .editorconfig file and using the extension. I cannot reliably reproduce this with a sample file, unfortunately.

I am using VS Code 1.9.1 and EditorConfig for VS Code 0.3.4.

> # EditorConfig is awesome: http://EditorConfig.org
> 
> root = true
>
> [*]
> charset = utf-8
> end_of_line = lf
> indent_size = 4
> indent_style = space
> insert_final_newline = true
> trim_trailing_whitespace = true
> 
> [*.md]>
> trim_trailing_whitespace = false
> 
> [{npm-shrinkwrap.json,package.json}]
> indent_style = space
> indent_size = 2

**Comment by SamVerschueren** [comment] 2017-03-01 21:14
Duplicate of #57

**Closed by SamVerschueren** 2017-03-01 21:14 UTC

**Comment by jedmao** [comment] 2017-03-11 19:21
@simonua fixed it properly in #116, published as v0.6.1.

**Comment by simonua** [comment] 2017-03-11 19:37
@jedmao, thank you kindly. Appreciate you.
