### ISSUE TITLE
editorconfig plugin breaks default functionality of vscode

### ISSUE THREAD

**Issue by kevinpeno** [editorconfig/editorconfig-vscode#114] opened 2017-03-07 19:15 UTC
### Expected behavior
If I edit the vscode workpsace settings related to editor configuration and have no editorconfig file in the root of the project, then vscode should use the workspace settings

### Actual behavior
When no editorconfig file is present and I have my workspace settings for editor set then editorconfig plugin uses the global settings

### Steps to reproduce the behavior

Set `.vscode/settings.json` to:

```json
{
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "editor.insertSpaces": false
}
```

Note that default global settings for these values are:

```json
{
  "editor.detectIndentation": true,
  "editor.tabSize": 4,
  "editor.insertSpaces": true
}
```

*Do not create an editorconfig file.*

Result should be that all use of `tab` should not be replaced and should have the size of two spaces.

**Comment by jedmao** [comment] 2017-03-07 20:39
This is by design. If you don't want this to happen, you have two options:
  1. Don't use a global `.editorconfig` file.
  2. Create an `.editorconfig` file at project root with `root = true` in it and nothing else.

**Comment by jedmao** [comment] 2017-03-07 20:42
Wait wait... I think I get what you're saying now. You're saying that even w/o a global `.editorconfig` file, the extension is pulling the global vscode settings and applying them over your local workspace settings, right?

**Comment by kevinpeno** [comment] 2017-03-07 22:28
Correct. If I uninstall the plugin then everything works as expected.

I also do not have a global level `.editorconfig` file. I only uses `.editorconfig` files at project levels and setup my editor how I like it by default using global editor user settings.

Use case: I'm dealing with a a project that will not let me commit an `.editorconfig` file nor add it to the `.gitignore` so in order to configure my editor I have to rely on workspace settings from vscode (the will allow me to add `.vscode` to the ignore file oddly enough...).

**Comment by jedmao** [comment] 2017-03-08 02:40
Thanks for the context. That sounds stressful! And you're right, that's funny that they are OK w/ allowing you to add the `.vscode` folder – haha! Some people!

I'll need some time to look into this and I'm afraid I don't have much time of recent. Would you be willing to take a stab at it and submit a PR?

**Comment by jedmao** [comment] 2017-03-08 03:39
@kevinpeno I am unable to reproduce the bug. I have this very project opened and I did the following:
  1. Deleted the `.editorconfig` file at project root.
  1. Commented out my `editor.detectIndentation`, `editor.tabSize` and `editor.insertSpaces` settings from my USER settings.
  1. Added the settings you mentioned above into my WORKSPACE settings.

I closed and reopened vscode and opened a js file that has tabs for indentation and everything looks good, I'm adding and removing tabs and everything is fine.

The only issues I've seen to date are when I open up a DIFF, then the indentation is all whacked. I need to look into that one.

**Comment by kevinpeno** [comment] 2017-03-09 23:52
I'll work on a test case this weekend with a clean project.

**Comment by jedmao** [comment] 2017-04-09 04:47
@kevinpeno if there are no updates I'd like to close this issue.

**Comment by kevinpeno** [comment] 2017-04-10 17:48
I'm sorry I haven't had much time on hand lately. Since you can't repro, feel free to close I guess. I'll just have to make sure I sit down and test it out and report back when I get some time. :)

**Comment by jedmao** [comment] 2017-04-10 18:11
We can always reopen when you revisit it and can repro.

**Closed by jedmao** 2017-04-10 18:11 UTC
Labels: Accepting PRs, bug, help wanted
