### ISSUE TITLE
Opening clean files in VSCode automatically marks it as dirty

### ISSUE THREAD

**Issue by anubrato** [editorconfig/editorconfig-vscode#59] opened 2016-07-11 07:50 UTC
Hi,

I noticed a behaviour in VSCode after installing this plugin. If I open a clean file (i.e. already committed), the file gets automatically marked as dirty. I suspect this has something to do with line ending conversions. I did not have this problem with the earlier plugin from Microsoft (from Chris Dias) which has now been deprecated in favour of this one.
I am on Windows 7 SP1 and using VS Code 1.3.0

Thanks

**Comment by SamVerschueren** [comment] 2016-07-11 07:54
duplicate of #57

**Closed by SamVerschueren** 2016-07-11 07:54 UTC
