### ISSUE TITLE
indent_size = 1 is not respected

### ISSUE THREAD

**Issue by domenic** [editorconfig/editorconfig-vscode#280] opened 2020-07-14 19:16 UTC
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself: not applicable since this is about the extension failing to do something, not about the extension breaking something

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.47.0`            | `0.15.1`             |

### Root `.editorconfig` File

```ini
root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_size = 2
indent_style = space
trim_trailing_whitespace = true

[demos/**]
insert_final_newline = false

[source]
indent_size = 1
max_line_length = 100
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | (unset)  | (unset)    |
| `editor.tabSize`               | `4`     | `2`     | (unset)       |
| `editor.trimAutoWhitespace`    | `true`  | (unset)  | (unset)    |
| `files.autoSave`               | `"off"` | (unset) | (unset)   |
| `files.insertFinalNewline`     | `false` | `true` | (unset)   |
| `files.trimTrailingWhitespace` | `false` | `true` | (unset)   |

### File opened

`source`

### Expected behavior

```ini
indent_size = 1
```

(as configured in the `.editorconfig` file and confirmed using `npm install -g editorconfig && editorconfig source`

### Actual behavior

```ini
indent_size = 2
```

(as shown in the VS code status bar and confirmed by pressing the <kbd>Tab</kbd> key)

### Additional comments or steps to reproduce

You can clone the repository for which this occurs at https://github.com/whatwg/html , although you may want to use `--depth=2` or similar since it's a large-ish repo with a lot of history.

I wonder if this has anything to do with `source` being extensionless?

**Comment by josiah-roberts** [comment] 2020-09-08 13:11
I'm also having this issue. Looking at the `EditorConfig` output, it sets `"insertSpaces"` and `"tabSize"` but does not change the actual indentation, just how many characters are added when you hit tab.

**Comment by jedmao** [comment] 2020-10-02 23:40
That's by design. EditorConfig helps you to config your editor on a per-file basis. It's not supposed to do transformations on file open, if that's what you were hoping for.

**Comment by jedmao** [comment] 2020-11-24 19:35
Closing, as I am unable to reproduce with the following configuration:

```editorconfig
[source]
indent_style = space
indent_size = 1
```

When opening the file named `source`, my status bar shows "Spaces: 1" and hitting tab, in fact, inserts a single space.

**Closed by jedmao** 2020-11-24 19:35 UTC
Labels: unable-repro
