### ISSUE TITLE
Unsaved changes for freshly opened files (nothing was changed)

### ISSUE THREAD

**Issue by Tarpsvo** [editorconfig/editorconfig-vscode#93] opened 2016-12-19 11:04 UTC
Originally in VSCode repo: https://github.com/Microsoft/vscode/issues/17525

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-theme-onedark|akamud|0.2.14|
|aurelia|AureliaEffect|0.1.12|
|Aurelia|behzad88|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|**EditorConfig**|**EditorConfig**|**0.3.4**|
|JavaScriptSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

I was unable to produce a reliably reproducable set of steps. It happens for some files in my project, not all.

When I open a new file from the left sidebar, it immediately shows up as being 'changed' and I have to save it again. After I save it, it shows up in Git as having changes, but no changes are actually displayed. When I try to stage the file, the 'changes'  disappear and the file disappears from the git status list. When I open the file again in VSCode, the cycle repeats.

I need some guidance in providing you with useful information, for I failed to find anything useful.

**Comment by SamVerschueren** [comment] 2016-12-19 11:11
Duplicate of #57

**Closed by SamVerschueren** 2016-12-19 11:11 UTC

**Comment by jedmao** [comment] 2017-03-11 19:19
@Tarpsvo fixed it properly in #116, published as v0.6.1.

**Comment by ianpaschal** [comment] 2018-11-14 16:31
I am experiencing this in 0.12.5 using VSCode 1.29.0, only with `.tsx` files. Haven't a clue why.

**Comment by jedmao** [comment] 2018-11-14 16:48
The most likely reason is a separate extension from this one. I work in TSX files all day long without issues.

**Comment by ianpaschal** [comment] 2018-11-14 17:36
Well, I disabled editorconfig and now it works... 🤷‍♂️

**Comment by jedmao** [comment] 2018-11-14 17:56
Try disabling all extensions except for EC and see if it works.
