### ISSUE TITLE
Previewing files in folder marks them as unsaved

### ISSUE THREAD

**Issue by pukhrajbal** [editorconfig/editorconfig-vscode#64] opened 2016-07-14 23:50 UTC
https://github.com/Microsoft/vscode/issues/9308

VSCode Version: 1.3.1
OS Version: Win 7

Steps to Reproduce:
1. Open a folder
2. Randomly select files to view their contents.
3. Files get marked as unsaved - even though nothing was changed.

This leaves a trail of all opened files which are marked as unsaved. To close them you have to individually click the "Dont save" button on prompt.

**Comment by jedmao** [comment] 2016-07-15 21:42
Duplicate of https://github.com/editorconfig/editorconfig-vscode/issues/57

**Closed by jedmao** 2016-07-15 21:42 UTC
