### ISSUE TITLE
Opening a file in VS Code marks it as dirty though no changes have been made

### ISSUE THREAD

**Issue by chambleton** [editorconfig/editorconfig-vscode#62] opened 2016-07-13 15:35 UTC
VSCode Version: 1.3.1
* only occurs with this extension installed

Steps to Reproduce:

1. Open any file in the editor
2. Note the file is marked as modified though no edits or changes have been made
3. Close the file; user is prompted to save.

**Comment by jedmao** [comment] 2016-07-13 17:05
Duplicate of #57

**Closed by jedmao** 2016-07-13 17:05 UTC
