### ISSUE TITLE
Editor on save changes scroll position

### ISSUE THREAD

**Issue by mister-glass** [editorconfig/editorconfig-vscode#158] opened 2017-07-14 08:25 UTC
Please fill-in this template.

- [X] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [X] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.14.1`            | `0.9.4`             |

### Root `.editorconfig` File

# top-most EditorConfig file
```ini
root = true
```
# Unix-style newlines with a newline ending every file
```ini
[*]
end_of_line = lf
insert_final_newline = false
charset = utf-8
indent_style = tab
indent_size = 4
tab_width = 4
trim_trailing_whitespace = true
```
# Matches multiple files with brace expansion notation
# Set default charset
```ini
[*.{sh,bash,conf}]
insert_final_newline = true
```
# 4 space indentation
```ini
[*.yml]
indent_style = space
indent_size = 2
tab_width = 2
```
# Tab indentation (no size specified)
```ini
[Makefile]
indent_style = tab
```
Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `false`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `true`  | `____`    |
| `files.autoSave`               | `"off"` | `"off"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `true` | `_____`   |

### File opened

`./foo.js`

### Expected behavior

On pressing Ctrl+S in a large file, when the editor is dirty (unsaved changes) and the line with the cursor is not currently in view, the editor scroll position should not change!

### Actual behavior

The editor scrolls back to the line where the cursor currently is.

### Additional comments or steps to reproduce

This bug was driving me nuts, especially at first when I thought something broke in VSCode in the last 2 or 3 updates, but actually I was relieved to find out this extension was causing this, because now I'm gonna uninstall this but not before I write this issue here. Hope you can reproduce it and work with it to see how annoying it can become :)

**Comment by jedmao** [comment] 2018-01-23 04:43
Unable to reproduce. I've edited a line, scrolled down until the cursor is out of view and hit <kbd>Ctrl+S</kbd>, but the scroll position remains the same. How did you verify this extension was the cause of it?

Closing until I can repro.

**Closed by jedmao** 2018-01-23 04:43 UTC
