### ISSUE TITLE
Annoying behavior while opening files with some settings behind

### ISSUE THREAD

**Issue by ketonal** [editorconfig/editorconfig-vscode#96] opened 2017-01-24 19:37 UTC
It started when I added following items to my user settings:
    "editor.formatOnType": true,
    "editor.formatOnSave": true

Now whenever I open any file, it's marked as edited - this is very annoying because I can't simply close it - I have to confirm because of *imaginary* (the file didn't changed really) changes that I've done fo this file. 

Steps to Reproduce:

1. Add to your user settings following items:
    "editor.formatOnType": true,
    "editor.formatOnSave": true
2. Restart VSC, open any file - it's instantaneously marked as edited.

The issue was first filed against VSC but it wasn't their fault after all - I've done my investigation and it seems that it's `editorconfig` fault unfortunately. Link to the issue on VSC repo: https://github.com/Microsoft/vscode/issues/19214

**Comment by jedmao** [comment] 2017-01-24 21:43
I don't think your `editor.formatOnType` or `formatOnSave` settings have anything to do with this issue at all. In fact, I think this is a duplicate of https://github.com/editorconfig/editorconfig-vscode/issues/57

**Closed by jedmao** 2017-01-24 21:43 UTC

**Comment by jedmao** [comment] 2017-03-11 19:21
@ketonal fixed it properly in #116, published as v0.6.1.
